### PR TITLE
Remove `#[allow(clippy::result_larg_err)]`, add `Box<Quote>`.

### PR DESCRIPTION
**Pull request by jcape**
What it says on the tin.

### CODE REVIEW

**Comment by jcape** [comment]
Current dependencies on/for this PR:
* main
  * **PR #39** <a href="https://app.graphite.dev/github/pr/mobilecoinofficial/deqs/39" target="_blank">Graphite</a> 
    * **PR #40** <a href="https://app.graphite.dev/github/pr/mobilecoinofficial/deqs/40" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinofficial/deqs/40?utm_source=stack-comment).

**Review by wjuan-mob — APPROVED** [review]

**Review by eranrund — APPROVED** [review]

**Comment by jcape** [comment]
@jcape queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/mobilecoinofficial/deqs/40).

**Comment by jcape** [comment]
@jcape merged this pull request with [Graphite](https://app.graphite.dev/github/pr/mobilecoinofficial/deqs/40).

**Pull request merged**
